name: PR Labeler

on:
  pull_request:
    types: [opened]
  workflow_call:

permissions: read-all|write-all

jobs:
  pr-labeler:
    permissions: read-all|write-all
    runs-on: ubuntu-latest
    steps:
      - uses: TimonVS/pr-labeler-action@v4.1.1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          configuration-path: .github/workflows/pr-labeler-properties.yml@dev
